// PDF export implementation using genpdf
// Generates professional PDF documents with metadata, summary, and transcript

use std::path::PathBuf;
use genpdf::{Document, elements, fonts};
use serde::Serialize;
use tauri::{AppHandle, Manager, Runtime};

use super::common::*;

#[derive(Debug, Serialize)]
pub struct MeetingPdfExportResult {
    pub meeting_id: String,
    pub output_path: Option<String>,
    pub wrote_file: bool,
    pub pdf_preview: Option<String>,
}

#[derive(Debug, Serialize)]
pub struct MeetingBatchExportResult {
    pub meeting_id: String,
    pub output_path: Option<String>,
    pub success: bool,
    pub error: Option<String>,
}

#[derive(Debug, Serialize)]
pub struct MeetingBatchExportResponse {
    pub results: Vec<MeetingBatchExportResult>,
}

/// Build a professional PDF document from export context
pub fn build_pdf_document(context: &ExportContext) -> Result<Vec<u8>, String> {
    // Use default font family
    let default_font = fonts::FontData::new(Vec::new(), None)
        .map_err(|e| format!("Failed to create font: {}", e))?;
    let font_family = fonts::FontFamily {
        regular: default_font.clone(),
        bold: default_font.clone(),
        italic: default_font.clone(),
        bold_italic: default_font,
    };
    
    let mut document = Document::new(font_family);
    document.set_title(&context.meeting.title);

    // Title
    document.push(elements::Paragraph::new(format!("Meeting: {}", context.meeting.title)));

    // Meeting info
    let duration_str = format_duration(context.meeting.duration_seconds);
    document.push(elements::Paragraph::new(format!("Date: {}", context.meeting.created_at)));
    document.push(elements::Paragraph::new(format!("Duration: {}", duration_str)));
    document.push(elements::Paragraph::new(format!("Source: {}", context.meeting.source_type)));
    document.push(elements::Paragraph::new(format!(
        "Language: {}",
        context.meeting.language.as_deref().unwrap_or("unknown")
    )));
    document.push(elements::Paragraph::new(format!(
        "Segments: {}",
        context.transcript_rows.len()
    )));
    
    // Add diarization info if available
    if let Some(status) = &context.meeting.diarization_status {
        if status == "completed" && !context.speaker_turns.is_empty() {
            let unique_speakers: std::collections::HashSet<_> = 
                context.speaker_turns.iter().map(|t| t.speaker_number).collect();
            document.push(elements::Paragraph::new(format!(
                "Speakers: {}",
                unique_speakers.len()
            )));
        }
    }

    document.push(elements::Paragraph::new(""));

    // Summary section
    if !context.summary_markdown.is_empty() {
        document.push(elements::Paragraph::new("Summary"));
        let summary_clean = clean_markdown_text(&context.summary_markdown);
        for line in summary_clean.lines().take(10) {
            document.push(elements::Paragraph::new(line));
        }
    } else {
        document.push(elements::Paragraph::new("No summary available."));
    }

    document.push(elements::Paragraph::new(""));

    // Full transcript section with speaker labels
    if !context.transcript_rows.is_empty() {
        document.push(elements::Paragraph::new("Transcript"));
        
        let transcript_lines = format_transcript_with_speakers(
            &context.transcript_rows,
            &context.speaker_turns,
            &context.vocabulary_rules,
        );
        
        // Limit to first 100 lines for PDF performance
        for line in transcript_lines.iter().take(100) {
            let display_line = if line.len() > 80 {
                format!("{}...", &line[..77])
            } else {
                line.clone()
            };

            document.push(elements::Paragraph::new(display_line));
        }
        
        if transcript_lines.len() > 100 {
            document.push(elements::Paragraph::new(format!(
                "... and {} more segments (truncated for PDF)",
                transcript_lines.len() - 100
            )));
        }
    }

    document.push(elements::Paragraph::new(""));
    document.push(elements::Paragraph::new(format!(
        "Generated by MeetFree v{} on {}",
        env!("CARGO_PKG_VERSION"),
        chrono::Utc::now().to_rfc3339()
    )));

    // Render to a temporary file then read it
    let temp_file = tempfile::NamedTempFile::new()
        .map_err(|e| format!("Failed to create temp file: {}", e))?;
    
    document
        .render_to_file(temp_file.path())
        .map_err(|e| format!("Failed to render PDF: {}", e))?;
    
    std::fs::read(temp_file.path())
        .map_err(|e| format!("Failed to read PDF: {}", e))
}

#[tauri::command]
pub async fn meeting_export_pdf<R: Runtime>(
    app: AppHandle<R>,
    state: tauri::State<'_, crate::state::AppState>,
    meeting_id: String,
    destination_root: Option<String>,
    preview: Option<bool>,
) -> Result<MeetingPdfExportResult, String> {
    export_meeting_pdf(
        &app,
        state.db_manager.pool(),
        &meeting_id,
        destination_root,
        preview.unwrap_or(false),
    )
    .await
}

pub async fn export_meeting_pdf<R: Runtime>(
    app: &AppHandle<R>,
    pool: &sqlx::SqlitePool,
    meeting_id: &str,
    destination_root: Option<String>,
    preview_mode: bool,
) -> Result<MeetingPdfExportResult, String> {
    let context = collect_export_context(pool, meeting_id).await?;
    let pdf_bytes = build_pdf_document(&context)?;

    if preview_mode {
        return Ok(MeetingPdfExportResult {
            meeting_id: meeting_id.to_string(),
            output_path: None,
            wrote_file: false,
            pdf_preview: Some(format!(
                "PDF generated successfully ({} bytes)",
                pdf_bytes.len()
            )),
        });
    }

    let destination_dir = resolve_single_destination_dir(app, &context.meeting, destination_root)?;
    let output_path = write_export_file_with_collision(
        &destination_dir,
        &context.meeting.title,
        "pdf",
        &pdf_bytes,
    )
    .await
    .map_err(|e| format!("Failed to write PDF export: {}", e))?;

    persist_export_path(pool, meeting_id, "pdf_export_path", &output_path).await?;

    Ok(MeetingPdfExportResult {
        meeting_id: meeting_id.to_string(),
        output_path: Some(output_path.to_string_lossy().to_string()),
        wrote_file: true,
        pdf_preview: None,
    })
}

#[tauri::command]
pub async fn meetings_export_pdf_batch<R: Runtime>(
    _app: AppHandle<R>,
    state: tauri::State<'_, crate::state::AppState>,
    meeting_ids: Vec<String>,
    destination_root: String,
    preview: Option<bool>,
) -> Result<MeetingBatchExportResponse, String> {
    if meeting_ids.is_empty() {
        return Ok(MeetingBatchExportResponse {
            results: Vec::new(),
        });
    }

    let pool = state.db_manager.pool();
    let root = std::path::PathBuf::from(destination_root);
    if !root.exists() {
        tokio::fs::create_dir_all(&root)
            .await
            .map_err(|e| format!("Failed to create destination root: {}", e))?;
    }

    let preview_mode = preview.unwrap_or(false);
    let mut results = Vec::with_capacity(meeting_ids.len());

    for meeting_id in meeting_ids {
        let export_result =
            export_single_batch_meeting_pdf(pool, &meeting_id, &root, preview_mode).await;
        results.push(export_result);
    }

    Ok(MeetingBatchExportResponse { results })
}

async fn export_single_batch_meeting_pdf(
    pool: &sqlx::SqlitePool,
    meeting_id: &str,
    root: &std::path::Path,
    preview_mode: bool,
) -> MeetingBatchExportResult {
    let result = async {
        let context = collect_export_context(pool, meeting_id).await?;
        let pdf_bytes = build_pdf_document(&context)?;

        if preview_mode {
            return Ok::<Option<PathBuf>, String>(None);
        }

        let subfolder = root.join(format!(
            "{}-{}",
            sanitize_filename(&context.meeting.title),
            &context.meeting.id
        ));
        let output_path = write_export_file_with_collision(
            &subfolder,
            &context.meeting.title,
            "pdf",
            &pdf_bytes,
        )
        .await
        .map_err(|e| format!("Failed to write PDF export: {}", e))?;

        persist_export_path(pool, meeting_id, "pdf_export_path", &output_path).await?;

        Ok(Some(output_path))
    }
    .await;

    match result {
        Ok(path) => MeetingBatchExportResult {
            meeting_id: meeting_id.to_string(),
            output_path: path.map(|p| p.to_string_lossy().to_string()),
            success: true,
            error: None,
        },
        Err(error) => MeetingBatchExportResult {
            meeting_id: meeting_id.to_string(),
            output_path: None,
            success: false,
            error: Some(error),
        },
    }
}

fn resolve_single_destination_dir<R: Runtime>(
    app: &AppHandle<R>,
    meeting: &MeetingExportData,
    destination_root: Option<String>,
) -> Result<std::path::PathBuf, String> {
    if let Some(root) = destination_root {
        return Ok(std::path::PathBuf::from(root));
    }

    if let Some(folder_path) = &meeting.folder_path {
        return Ok(std::path::PathBuf::from(folder_path));
    }

    let app_data = app
        .path()
        .app_data_dir()
        .map_err(|e| format!("Failed to resolve app data directory: {}", e))?;
    Ok(app_data.join("exports").join(&meeting.id))
}

fn format_duration(seconds: Option<f64>) -> String {
    match seconds {
        Some(s) => {
            let hours = (s / 3600.0).floor() as u32;
            let minutes = ((s % 3600.0) / 60.0).floor() as u32;
            let secs = (s % 60.0).floor() as u32;
            format!("{:02}:{:02}:{:02}", hours, minutes, secs)
        }
        None => "unknown".to_string(),
    }
}

fn clean_markdown_text(text: &str) -> String {
    text.replace("## ", "")
        .replace("# ", "")
        .replace("- ", "• ")
        .replace("**", "")
        .replace("*", "")
        .trim()
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn format_duration_calculates_correctly() {
        assert_eq!(format_duration(Some(3665.0)), "01:01:05");
        assert_eq!(format_duration(Some(60.0)), "00:01:00");
        assert_eq!(format_duration(Some(3600.0)), "01:00:00");
        assert_eq!(format_duration(None), "unknown");
    }

    #[test]
    fn clean_markdown_removes_formatting() {
        assert_eq!(clean_markdown_text("## Title"), "Title");
        assert_eq!(clean_markdown_text("**bold** text"), "bold text");
        assert_eq!(clean_markdown_text("- item"), "• item");
    }
}
